### ISSUE TITLE
Port rev1 Sponsor View

### ISSUE THREAD

**Issue by johnnynibbles** [cjr-consulting/DartLeague#4]
manage/sponsor

Convert the list, create, and edit views

**Comment by Shemptankerous** [comment]
Is this done?  It looks like the related code has been merged to me.  Was there something outstanding?

**Comment by johnnynibbles** [comment]
it does look like it.  There was a pull request completed.  it didn't close automatically because the comment for the pull request didn't include the resolves command.

Since the ticket is also on the project board, I think it needs to be manually moved to the completed column.
